export const labelsNb = {
  basemap: {
    controlLabel: 'Bakgrunnskart',
    geonorge: 'Topografisk Norgeskart farge',
    geonorgeGraatone: 'Topografisk Norgeskart gråtone',
    osm: 'OpenStreetMap',
  },
  tools: {
    title: 'Verktøy',
    measure: 'Mål avstand',
    export: 'Eksporter data',
    cancel: 'Avbryt',
    download: 'Last ned',
  },
  legend: {
    title: 'Tegnforklaring',
    samplingPoint: 'Prøvetakingspunkt',
    overflowPoint: 'Overløpspunkt',
    overflowLine: 'Overløpsledning',
    spoLine: 'SPO ledning',
    afoLine: 'AFO ledning',
    faerderKommune: 'Færder kommune',
    tonsbergKommune: 'Tønsberg kommune',
    tonsbergRenseanlegg: 'Tønsberg renseanlegg',
  },
  search: {
    placeholderSampling: 'Søk i navn eller vannlok...',
    empty: 'Ingen treff',
  },
  filters: {
    filterBySampleType: 'Filtrer på prøvetype',
    filterByOwner: 'Filtrer på eier',
    reset: 'Nullstill',
    sampleTypeTitle: 'Prøvetype',
    ownerTitle: 'Eier',
    waterSample: 'Vannprøve',
    sedimentSample: 'Sedimentprøve',
    softBottomFauna: 'Bløtbunnsfauna',
  },
  export: {
    title: 'Eksporter data',
    chooseDataType: 'Velg datatype',
    chooseFormat: 'Velg format',
    geojson: 'GeoJSON',
    csv: 'CSV',
    noData: 'Ingen data å eksportere',
    samplingPoints: 'Prøvetakingspunkter',
    overflowPoints: 'Overløpspunkter',
  },
  fields: {
    registered: 'Registrert',
    function: 'Funksjon',
    station: 'Stasjon',
    length: 'Lengde',
    material: 'Materiale',
    dimension: 'Dimensjon',
    sampleTypes: 'Prøvetyper',
    waterLocationCode: 'Vannlokalitetkode',
    unknown: 'Ukjent',
    noneRegistered: 'Ingen registrert',
    points: 'Punkter',
    lines: 'Ledninger',
  },
  coordinates: {
    wgs84: 'WGS84 (GPS)',
    utm32n: 'UTM Zone 32N (EUREF89)',
    copyWgs84: 'Kopier WGS84',
    copyUtm32n: 'Kopier UTM32N',
  },
  common: {
    yes: 'Ja',
    no: 'Nei',
    unknown: 'Ukjent',
    emptyValue: '?',
  },
};

export default labelsNb;
