export const layers = [
  {
    id: 'prv_punkt',
    label: 'Prøvetakingspunkt',
    pluralLabel: 'Prøvetakingspunkter',
    type: 'point',
    geometryTypes: ['Point'],
    dataPath: '../data/prv_punkt.json',
    dataImport: '../data/prv_punkt.json',
    defaultVisible: true,
    showInSidebar: true,
    renderOrder: 30,
    minZoom: null,
    labelMinZoom: 14,
    idField: 'fid',
    fallbackIdFields: ['MPNT_GUID', 'PSID', 'navn', 'vannlok-kode'],
    titleField: 'navn',
    subtitleFields: ['vannlok-kode', 'PSID'],
    searchFields: ['navn', 'vannlok-kode'],
    displayFields: [
      'navn',
      'vannlok-kode',
      'PSID',
      'vannprøve',
      'sedimentprøve',
      'Bløtbunnsfauna',
      'Eier',
      'DATEREG',
      'DATECHANGE',
      'utm_x',
      'utm_y',
    ],
    popupFields: [
      'navn',
      'vannlok-kode',
      'PSID',
      'vannprøve',
      'sedimentprøve',
      'Bløtbunnsfauna',
      'DATEREG',
      'utm_x',
      'utm_y',
    ],
    sidebarFields: {
      title: ['navn', 'PSID'],
      subtitle: ['vannlok-kode', 'PSID'],
    },
    exportFields: [
      'fid',
      'navn',
      'vannlok-kode',
      'PSID',
      'vannprøve',
      'sedimentprøve',
      'Bløtbunnsfauna',
      'DATEREG',
      'utm_x',
      'utm_y',
      'lng',
      'lat',
    ],
    symbol: {
      shape: 'circle',
      radius: 6,
      strokeColor: '#c026d3',
      fillColor: '#e879f9',
      strokeWidth: 2,
      fillOpacity: 0.8,
      selectedGlowColor: '#fbbf24',
      labelField: 'navn',
    },
    styleByProperty: [
      {
        id: 'owner',
        field: 'Eier',
        target: 'strokeColor',
        values: {
          FK: {
            label: 'Færder kommune',
            strokeColor: '#c026d3',
          },
          TK: {
            label: 'Tønsberg kommune',
            strokeColor: '#22c55e',
          },
          TR: {
            label: 'Tønsberg renseanlegg',
            strokeColor: '#ff4500',
          },
        },
      },
    ],
    filters: [
      {
        id: 'sampleType',
        label: 'Prøvetype',
        type: 'booleanAny',
        options: [
          {
            id: 'vannprøve',
            label: 'Vannprøve',
            field: 'vannprøve',
          },
          {
            id: 'sedimentprøve',
            label: 'Sedimentprøve',
            field: 'sedimentprøve',
          },
          {
            id: 'bløtbunnsfauna',
            label: 'Bløtbunnsfauna',
            field: 'Bløtbunnsfauna',
          },
        ],
      },
      {
        id: 'owner',
        label: 'Eier',
        type: 'equalsAny',
        field: 'Eier',
        options: [
          {
            id: 'ownerFK',
            label: 'Færder kommune',
            value: 'FK',
            color: '#c026d3',
          },
          {
            id: 'ownerTK',
            label: 'Tønsberg kommune',
            value: 'TK',
            color: '#22c55e',
          },
          {
            id: 'ownerTR',
            label: 'Tønsberg renseanlegg',
            value: 'TR',
            color: '#ff4500',
          },
        ],
      },
    ],
  },
  {
    id: 'ult_punkt',
    label: 'Overløpspunkt',
    pluralLabel: 'Overløpspunkter',
    type: 'point',
    geometryTypes: ['Point'],
    dataPath: '../data/ult_punkt.json',
    dataImport: '../data/ult_punkt.json',
    defaultVisible: true,
    showInSidebar: true,
    renderOrder: 20,
    minZoom: 13,
    labelMinZoom: 14,
    idField: 'fid',
    fallbackIdFields: ['PSID', 'REF', 'STATION'],
    titleField: 'REF',
    subtitleFields: ['PSID', 'STATION'],
    searchFields: ['REF', 'STATION', 'PSID'],
    displayFields: [
      'REF',
      'STATION',
      'PSID',
      'FCODE',
      'FUNC',
      'YEAR',
      'Z',
      'DATEREG',
      'DATECHANGE',
      'utm_x',
      'utm_y',
    ],
    popupFields: ['REF', 'PSID', 'STATION', 'FUNC', 'DATEREG', 'utm_x', 'utm_y'],
    sidebarFields: {
      title: ['navn', 'REF', 'PSID'],
      subtitle: ['PSID'],
    },
    exportFields: [
      'fid',
      'REF',
      'STATION',
      'PSID',
      'DATEREG',
      'utm_x',
      'utm_y',
      'lng',
      'lat',
    ],
    symbol: {
      shape: 'square',
      radius: 7,
      strokeColor: '#f97316',
      fillColor: '#fb923c',
      strokeWidth: 2,
      fillOpacity: 0.8,
      selectedGlowColor: '#fbbf24',
      labelField: 'REF',
    },
    styleByProperty: [
      {
        id: 'overflowByFcode',
        field: 'FCODE',
        values: {
          OVL: {
            label: 'Overløpspunkt',
            strokeColor: '#f97316',
            fillColor: '#fb923c',
          },
        },
      },
    ],
  },
  {
    id: 'utl_ledning',
    label: 'Overløpsledning',
    pluralLabel: 'Overløpsledninger',
    type: 'line',
    geometryTypes: ['LineString', 'MultiLineString'],
    dataPath: '../data/utl_ledning.json',
    dataImport: '../data/utl_ledning.json',
    defaultVisible: true,
    showInSidebar: true,
    renderOrder: 10,
    minZoom: 13,
    labelMinZoom: null,
    idField: 'fid',
    fallbackIdFields: ['LINE_GUID', 'LSID', 'FROM_PSID', 'TO_PSID'],
    titleField: 'FCODE',
    subtitleFields: ['LSID', 'LENGTH'],
    searchFields: ['LSID', 'FCODE', 'FCODEGROUP', 'MATERIAL', 'DIM'],
    displayFields: [
      'LSID',
      'FCODE',
      'FCODEGROUP',
      'LENGTH',
      'MATERIAL',
      'DIM',
      'YEAR',
      'DATEREG',
      'DATECHANGE',
      'FROM_PSID',
      'TO_PSID',
      'LINE_GUID',
    ],
    popupFields: ['FCODE', 'LSID', 'LENGTH', 'MATERIAL', 'DIM'],
    sidebarFields: {
      title: ['FCODE', 'LSID'],
      subtitle: ['LENGTH'],
    },
    exportFields: [
      'fid',
      'LSID',
      'FCODE',
      'FCODEGROUP',
      'LENGTH',
      'MATERIAL',
      'DIM',
      'YEAR',
      'DATEREG',
      'DATECHANGE',
      'FROM_PSID',
      'TO_PSID',
      'LINE_GUID',
    ],
    symbol: {
      shape: 'line',
      color: '#3b82f6',
      weight: 4,
      opacity: 0.8,
      dashArray: '10, 10',
      selectedGlowColor: '#fbbf24',
      selectedWeight: 8,
    },
    styleByProperty: [
      {
        id: 'lineByFcode',
        field: 'FCODE',
        values: {
          SPO: {
            label: 'SPO ledning',
            color: '#22c55e',
            dashArray: '10, 10',
          },
          AFO: {
            label: 'AFO ledning',
            color: '#ef4444',
            dashArray: '10, 10',
          },
        },
        default: {
          label: 'Ledning',
          color: '#3b82f6',
          dashArray: '10, 10',
        },
      },
    ],
  },
];

export const defaultLayerId = 'prv_punkt';

export default layers;
